name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - run: ./gradlew detekt

  test:
    runs-on: ubuntu-latest
    steps:
      - run: ./gradlew test  